# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0bf8e4890f1f140b62bf6696121d035a0602890f73788c71e27b88a408f9c5f6bd8bda4e59fe97fa7603fe69462e951ef57c41b2da0bc1be50e16b0dd0af9269

test:
  secret_key_base: ebdf054315e764374c59f52a9bded8d59b3fe8d7279f4381fa60f1fbb3cf1cae3cd2a1d3ea3cc44a7c48f3b47affa4647d1cd45bcd27dd2222ef11bac0195228

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
